version: "3"

services:

  runtime-setup:
    image: netty:centos-7-1.17
    build:
      args:
        java_version : "zulu@1.17.0-0"

  build:
    image: netty:centos-7-1.17

  build-leak:
    image: netty:centos-7-1.17

  build-boringssl-static:
    image: netty:centos-7-1.17

  build-leak-boringssl-static:
    image: netty:centos-7-1.17

  shell:
    image: netty:centos-7-1.17
