version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.16
    build:
      args:
        java_version : "adopt@1.16.0-1"

  build:
    image: netty:centos-6-1.16

  build-leak:
    image: netty:centos-6-1.16

  build-boringssl-static:
    image: netty:centos-6-1.16

  build-leak-boringssl-static:
    image: netty:centos-6-1.16

  shell:
    image: netty:centos-6-1.16
